### ISSUE TITLE
izzy.io.google.authenticate -- refresh request fails with invalid scope message

### ISSUE THREAD

**Issue by doclockh** [LockhartLab/izzy#1]
```>>> x.refresh(Request())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Chris\Anaconda3\lib\site-packages\google\oauth2\credentials.py", line 152, in refresh
    self._scopes,
  File "C:\Users\Chris\Anaconda3\lib\site-packages\google\oauth2\_client.py", line 244, in refresh_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "C:\Users\Chris\Anaconda3\lib\site-packages\google\oauth2\_client.py", line 120, in _token_endpoint_request
    _handle_error_response(response_body)
  File "C:\Users\Chris\Anaconda3\lib\site-packages\google\oauth2\_client.py", line 60, in _handle_error_response
    raise exceptions.RefreshError(error_details, response_body)
google.auth.exceptions.RefreshError: ('invalid_scope: Some requested scopes were invalid. {invalid=[a, c, d, e, g, h, i, l, m, ., /, o, p, r, s, t, u, w, :]}', '{\n  "error": "invalid_scope",\n  "error_description": "Some requested scopes were invalid. {invalid\\u003d[a, c, d, e, g, h, i, l, m, ., /, o, p, r, s, t, u, w, :]}",\n  "error_uri": "http://code.google.com/apis/accounts/docs/OAuth2.html"\n}')```

**Comment by doclockh** [comment]
The issue is fixed by turning endpoint in `izzy.io.google.authenticate` to a list
```flow = InstalledAppFlow.from_client_secrets_file(credentials, [endpoint])```
